# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = GaugeBoardWidget
DESTDIR = ../x64/Debug
CONFIG += staticlib debug
DEFINES += GAUGEBOARDWIDGET_LIB BUILD_STATIC
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(GaugeBoardWidget.pri)
